# Generated by Django 5.0.6 on 2024-07-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.CharField(default='text edition', max_length=1024),
        ),
    ]
