# Generated by Django 5.0.6 on 2024-07-02 14:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_category_categoryarticle_article_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(related_name='user_like', through='article.UserArticle', to=settings.AUTH_USER_MODEL),
        ),
    ]
