# Generated by Django 5.0.6 on 2024-07-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_remove_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(through='article.CategoryArticle', to='article.category'),
        ),
    ]
